name: NoDevFee XMRIG (Linux)

on:
  # Manueel starte
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    container: ubuntu:24.04

    steps:
      - name: Checkout Repository master branch
        uses: actions/checkout@v2
        with:
          repository: xmrig/xmrig

      - name: Build project on Ubuntu
        run: |
          yes | apt update
          apt install -y git build-essential cmake automake libtool autoconf
          echo "XMRIG_VERSION="`cat src/version.h | grep -Eo "APP_VERSION\s+\"(.+?)\"" | awk -F "\"" '{print $2}'` >> $GITHUB_ENV
          sed -i 's/DonateLevel = 1/DonateLevel = 0/g' src/donate.h
          ./build_deps.sh && cd ../build
          cmake .. 
          make -j$(nproc) 
          tar cfz ubuntu_build.tar.gz xmrig
      - name: Upload Ubuntu build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: xmrig-${{ env.XMRIG_VERSION }}
          path: ubuntu_build.tar.gz
